In [1]:
###TENSORS
# A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

# Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

# default data type of float32.

# More suitable for deep learning than a numpy array.

In [2]:

import torch
import numpy as np



**LISTS**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAYS**

In [4]:
np1 = np.random.rand(3,4)
np1



array([[0.09532139, 0.50204632, 0.92028409, 0.48615838],
       [0.64558131, 0.08432526, 0.11150943, 0.39842084],
       [0.80425662, 0.66541641, 0.9510379 , 0.80042435]])

In [5]:

np1.dtype

dtype('float64')

**TENSORS**

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype


tensor([[ 0.3646, -1.3360, -0.7767,  0.4635],
        [ 0.3859,  0.0717,  0.3857, -0.6476],
        [-0.8292,  0.1829, -1.0210,  0.1908]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0953, 0.5020, 0.9203, 0.4862],
        [0.6456, 0.0843, 0.1115, 0.3984],
        [0.8043, 0.6654, 0.9510, 0.8004]], dtype=torch.float64)